### ISSUE TITLE
Libraries missing

### ISSUE THREAD

**Issue by Davierooker** [DzikuVx/QmuBeaconLocator#2]
Are some libraries missing? Also getting a "define hardware" error message.

**Comment by DzikuVx** [comment]
You have to select ARDUINO_ESP32_DEV as a board. This is the genral ESP32 target

**Comment by Davierooker** [comment]
Hi Pawel,
Thanks for the reply, I'm a bit new to Arduino.
    On Tuesday, 14 May 2019, 11:59:44 BST, Paweł Spychalski <notifications@github.com> wrote:  
 
 
You have to select ARDUINO_ESP32_DEV as a board. This is the genral ESP32 target
